---
repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.1.0
    hooks:
      - id: tofu_fmt
      - id: tofu_trivy
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.0
    hooks:
      - id: yamllint
